[buildPlans.devka]
family = "Devka"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
no-ligation = true

[buildPlans.devka.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-q = "curly-tailed"
f = "flat-hook"
g = "single-storey-flat-hook-serifless"
l = "tailed-serifed"
t = "flat-hook"
eszet = "sulzbacher-descending"
cyrl-capital-ze = "bilateral-serifed"
four = "closed"
brace = "curly"
ampersand = "upper-open"
at = "short"
question = "corner-flat-hooked"

[buildPlans.devka.variants.italic]
f = "flat-hook-tailed"
h = "tailed"
k = "diagonal-tailed-cursive-serifless"
m = "tailed"
n = "tailed"
v = "cursive"
w = "cursive"

[buildPlans.devka.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.devka.weights.book]
shape = 450
menu = 450
css = 450

[buildPlans.devka.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.devka.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.devka.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.devka.weights.extrabold]
shape = 800
menu = 800
css = 800

[buildPlans.devka.weights.heavy]
shape = 900
menu = 900
css = 900

[buildPlans.devka.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.devka.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.devka.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
